using System;
using System.IO;
using System.Linq;
using GenomeAnalysis.Core.Genome;
using GenomeAnalysis.Core.Parsing;
using Xunit;

namespace GenomeAnalysis.Tests
{
    public class GenomeFileReaderTests
    {
        private static GenomeFileReader FromText(string text) =>
            GenomeFileReader.Create(new StringReader(text));

        private const string TwentyThreeAndMe =
            "# This data file generated by 23andMe at: Sat Jan 11 04:12:37 2014\n" +
            "# We are using reference human assembly build 37 (also known as Annotation Release 104).\n" +
            "# rsid\tchromosome\tposition\tgenotype\n" +
            "rs4477212\t1\t82154\tAA\n" +
            "rs3094315\t1\t752566\tAG\n" +
            "rs28897696\t17\t41244936\t--\n" +
            "i5000940\t1\t82154\tAA\n" +
            "rs2534636\tY\t2655180\tC\n" +
            "rs1799752\t17\t61565891\tII\n";

        private const string AncestryDna =
            "#AncestryDNA raw data download\n" +
            "#Data is formatted using human reference build 37 (also known as GRCh37).\n" +
            "rsid\tchromosome\tposition\tallele1\tallele2\n" +
            "rs4477212\t1\t82154\tA\tA\n" +
            "rs3094315\t1\t752566\tA\tG\n" +
            "rs28897696\t17\t41244936\t0\t0\n";

        [Fact]
        public void DetectsTwentyThreeAndMeFromHeader()
        {
            using (var reader = FromText(TwentyThreeAndMe))
            {
                Assert.Equal(GenomeFileProvider.TwentyThreeAndMe, reader.Header.Provider);
                Assert.Equal(GenomeBuild.GRCh37, reader.Header.Build);
            }
        }

        [Fact]
        public void DetectsAncestryDnaAndItsTwoAlleleColumns()
        {
            using (var reader = FromText(AncestryDna))
            {
                Assert.Equal(GenomeFileProvider.AncestryDna, reader.Header.Provider);
                Assert.Equal(GenomeBuild.GRCh37, reader.Header.Build);

                var calls = reader.ReadCalls().ToList();
                var heterozygous = calls.Single(c => c.MarkerId == "rs3094315");

                Assert.Equal(new Genotype(Nucleotide.A, Nucleotide.G), heterozygous.Genotype);
            }
        }

        [Fact]
        public void ProviderIsDetectedFromLayoutWhenTheHeaderIsStripped()
        {
            // Files get edited and re-saved. Two allele columns identify AncestryDNA
            // even with no provider line left.
            using (var reader = FromText("rsid\tchromosome\tposition\tallele1\tallele2\nrs1\t1\t1\tA\tG\n"))
            {
                Assert.Equal(GenomeFileProvider.AncestryDna, reader.Header.Provider);
            }
        }

        [Fact]
        public void NoCallsAreReadAsAbsentGenotypes_NotAsMalformedRows()
        {
            using (var reader = FromText(TwentyThreeAndMe))
            {
                var calls = reader.ReadCalls().ToList();
                var noCall = calls.Single(c => c.MarkerId == "rs28897696");

                Assert.True(noCall.IsNoCall);
                Assert.Null(noCall.Genotype);
                Assert.Equal("--", noCall.RawGenotypeToken);
                Assert.Equal(0, reader.Statistics.MalformedRows);
            }
        }

        [Fact]
        public void AncestryNoCallsUseZeroRatherThanDashes()
        {
            using (var reader = FromText(AncestryDna))
            {
                var calls = reader.ReadCalls().ToList();

                Assert.True(calls.Single(c => c.MarkerId == "rs28897696").IsNoCall);
                Assert.Equal(0, reader.Statistics.MalformedRows);
            }
        }

        [Fact]
        public void IndelMarkersAreNotTreatedAsGenotypes()
        {
            using (var reader = FromText(TwentyThreeAndMe))
            {
                var calls = reader.ReadCalls().ToList();
                var indel = calls.Single(c => c.MarkerId == "rs1799752");

                Assert.True(indel.IsNoCall);
                Assert.Equal("II", indel.RawGenotypeToken);
            }
        }

        [Fact]
        public void HemizygousCallsOnYAreReadAsSingleAllele()
        {
            using (var reader = FromText(TwentyThreeAndMe))
            {
                var calls = reader.ReadCalls().ToList();
                var yCall = calls.Single(c => c.MarkerId == "rs2534636");

                Assert.True(yCall.Genotype!.Value.IsHemizygous);
                Assert.True(yCall.Chromosome.IsAlwaysHemizygous);
                Assert.Equal(1, reader.Statistics.HemizygousCalls);
            }
        }

        [Fact]
        public void ProviderInternalIdsAreCountedSeparately()
        {
            using (var reader = FromText(TwentyThreeAndMe))
            {
                var calls = reader.ReadCalls().ToList();

                Assert.False(calls.Single(c => c.MarkerId == "i5000940").IsRsId);
                Assert.Equal(1, reader.Statistics.ProviderInternalIds);
            }
        }

        [Fact]
        public void MissingBuildIsWarnedAbout_NotAssumed()
        {
            using (var reader = FromText("# rsid\tchromosome\tposition\tgenotype\nrs1\t1\t1\tAA\n"))
            {
                Assert.Equal(GenomeBuild.Unknown, reader.Header.Build);
                Assert.Contains(reader.Header.Warnings, w => w.Contains("reference build"));
            }
        }

        [Fact]
        public void UnrecognisedProviderIsWarnedAbout()
        {
            using (var reader = FromText("rsid\tchromosome\tposition\tgenotype\nrs1\t1\t1\tAA\n"))
            {
                Assert.False(reader.Header.IsRecognised);
                Assert.Contains(reader.Header.Warnings, w => w.Contains("not recognised"));
            }
        }

        [Fact]
        public void TruncatedFileYieldsWhatItCan_WithoutThrowing()
        {
            using (var reader = FromText("# rsid\tchromosome\tposition\tgenotype\nrs1\t1\t100\tAA\nrs2\t1"))
            {
                var calls = reader.ReadCalls().ToList();

                Assert.Single(calls);
                Assert.Equal(1, reader.Statistics.MalformedRows);
            }
        }

        [Fact]
        public void EmptyFileProducesNoCallsAndAWarning()
        {
            using (var reader = FromText(string.Empty))
            {
                Assert.Empty(reader.ReadCalls().ToList());
                Assert.Contains(reader.Header.Warnings, w => w.Contains("column header"));
            }
        }

        [Fact]
        public void ColumnsAreLocatedByNameNotByPosition()
        {
            // A reordered export must still parse: providers have moved columns
            // between versions.
            using (var reader = FromText("# genotype\tposition\tchromosome\trsid\nAG\t752566\t1\trs3094315\n"))
            {
                var call = reader.ReadCalls().Single();

                Assert.Equal("rs3094315", call.MarkerId);
                Assert.Equal(752566, call.Position);
                Assert.Equal(new Genotype(Nucleotide.A, Nucleotide.G), call.Genotype);
            }
        }

        [Fact]
        public void CommaSeparatedQuotedFormatIsSupported()
        {
            // MyHeritage and FTDNA quote every field and use commas.
            const string text =
                "# MyHeritage DNA raw data. build 37\n" +
                "RSID,CHROMOSOME,POSITION,RESULT\n" +
                "\"rs3094315\",\"1\",\"752566\",\"AG\"\n";

            using (var reader = FromText(text))
            {
                Assert.Equal(GenomeFileProvider.MyHeritage, reader.Header.Provider);

                var call = reader.ReadCalls().Single();

                Assert.Equal("rs3094315", call.MarkerId);
                Assert.Equal(new Genotype(Nucleotide.A, Nucleotide.G), call.Genotype);
            }
        }

        [Fact]
        public void ReadingTwiceIsRefused_BecauseTheStreamCannotRewind()
        {
            using (var reader = FromText(TwentyThreeAndMe))
            {
                reader.ReadCalls().ToList();

                Assert.Throws<InvalidOperationException>(() => reader.ReadCalls().ToList());
            }
        }

        [Fact]
        public void StatisticsAccountForEveryRow()
        {
            using (var reader = FromText(TwentyThreeAndMe))
            {
                reader.ReadCalls().ToList();
                var stats = reader.Statistics;

                Assert.Equal(6, stats.TotalRows);
                Assert.Equal(stats.TotalRows, stats.CalledGenotypes + stats.NoCalls + stats.MalformedRows);
            }
        }
    }

    public class FixtureFileTests
    {
        private static string FixturePath(string name) =>
            Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Fixtures", name);

        [Fact]
        public void TwentyThreeAndMeFixtureParses()
        {
            var path = FixturePath("23andme-sample.txt");

            using (var reader = GenomeFileReader.Open(path))
            {
                var calls = reader.ReadCalls().ToList();

                Assert.Equal(GenomeFileProvider.TwentyThreeAndMe, reader.Header.Provider);
                Assert.Equal(GenomeBuild.GRCh37, reader.Header.Build);
                Assert.True(calls.Count > 30);
                Assert.Equal(0, reader.Statistics.MalformedRows);
                Assert.True(reader.Statistics.NoCalls >= 2);
                Assert.True(reader.Statistics.HemizygousCalls >= 3);
            }
        }

        [Fact]
        public void AncestryDnaFixtureParses()
        {
            var path = FixturePath("ancestrydna-sample.txt");

            using (var reader = GenomeFileReader.Open(path))
            {
                var calls = reader.ReadCalls().ToList();

                Assert.Equal(GenomeFileProvider.AncestryDna, reader.Header.Provider);
                Assert.True(calls.Count > 15);
                Assert.Equal(0, reader.Statistics.MalformedRows);
            }
        }
    }
}
